export const ACTION_TYPE = {
  LOGIN: "LOGIN",
  SET_ACTIVE_TAB: "SET_ACTIVE_TAB",
  INCREASE_QUANTITY: "INCREASE_QUANTITY",
  DECREASE_QUANTITY: "DECREASE_QUANTITY",
  SET_LOGIN_DATA: "SET_LOGIN_DATA",
  CLEAR_USER_DATA: "CLEAR_USER_DATA",
  SET_SELECTED_RESTAURANT: "SET_SELECTED_RESTAURANT",
  CLEAR_RESTAURANT_DATA: "CLEAR_RESTAURANT_DATA",
  ADD_DISHES: "ADD_DISHES",
};
