export const CONSTANTS = {
  LOGIN_TAB: "LOGIN_TAB",
  CUSTOMER_SIGNUP: "CUSTOMER_SIGNUP",
  RESTAURANT_SIGNUP: "RESTAURANT_SIGNUP",
  RESTAURANT_SIGNIN: "RESTAURANT_SIGNIN",
  CUSTOMER_SIGNIN: "CUSTOMER_SIGNIN",
  DASHBOARD: "DASHBOARD",
};
